### ISSUE TITLE
Add `chain` into configuration

### ISSUE THREAD

**Issue by stephpy** [rezzza/ShortyBundle#7]
```yaml
rezzza_shorty:
   default_provider: chain
   providers:
      google:
        ....
      bitly:
         ...
      chain:
        providers: [google, bitly]
```
Then:

```php
$this->get('rezzza_shorty')->shorten('http:............');
```

Second solution more complicated to implement.
